### ISSUE TITLE
Connecting existing accounts and front-end shortcodes

### ISSUE THREAD

**Issue by ghost** [Yeghro/WordpressNostrLogin#1]
Out of all the WP nostr auth apps, your implementation rules. Adding connect for existing accounts and front-end shortcodes would complete it nicely.

**Comment by Yeghro** [comment]
> Out of all the WP nostr auth apps, your implementation rules. Adding connect for existing accounts and front-end shortcodes would complete it nicely.

I'm delighted to hear you like the plug-in, thank you for the kind words.  I have been meaning to setup the shortcodes, other users have asked about them as well, I will try to get that setup, this was a good reminder.  

Can you please elaborate on what you mean by "adding connect for existing accounts"?  I don't think I understand.

**Comment by ghost** [comment]
Well, existing users, logged in already, can link their nostr account, by 'connecting' or linking it, otherwise it's all new accounts. I copied what was added to the usermeta as a test sign-in with my extension, and changed the id of the metadata fields, two of them associated to my existing id, to link my nostr account with my existing account. Like most platforms do when you "Link" another social account ..

**Comment by Yeghro** [comment]
> Well, existing users, logged in already, can link their nostr account, by 'connecting' or linking it, otherwise it's all new accounts. I copied what was added to the usermeta as a test sign-in with my extension, and changed the id of the metadata fields, two of them associated to my existing id, to link my nostr account with my existing account. Like most platforms do when you "Link" another social account ..

I see what you're saying.  Makes total sense.  I'll try to get that update for you soon as I can.

**Comment by Yeghro** [comment]
> > Well, existing users, logged in already, can link their nostr account, by 'connecting' or linking it, otherwise it's all new accounts. I copied what was added to the usermeta as a test sign-in with my extension, and changed the id of the metadata fields, two of them associated to my existing id, to link my nostr account with my existing account. Like most platforms do when you "Link" another social account ..
> 
> I see what you're saying. Makes total sense. I'll try to get that update for you soon as I can.

I was able to get the feature implemented it is available in the wordpress plugin store as new version 1.3.  If you prefer github checkout the accountsync branch.

**Comment by Yeghro** [comment]
closing this out

**Comment by ghost** [comment]
You are a superstar, great stuff !
